project_id = "ljfjadtphwxbghghvhjk"

[functions.create-staff-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.auto-close-events]
verify_jwt = false

[functions.auto-break-stop]
verify_jwt = false

[functions.generate-shift-calendar]
verify_jwt = false