estimated_rows;schemaname;table_name
338;public;audit_logs
81;public;production_events
21;public;production_counts
18;public;shift_calendar
17;public;production_standards
11;public;downtime_reasons
11;public;products
10;public;machines
8;public;defect_reasons
8;public;oee_snapshots
6;public;user_profiles
3;public;lines
3;public;shift_approvals
2;public;setup_reasons
2;public;user_machine_permissions
2;public;holidays
1;public;shifts
1;public;planned_time_templates
1;public;plants
1;public;companies
1;public;machine_permission_groups
0;public;user_plant_permissions
0;public;machine_permission_group_machines
0;public;user_permission_groups
0;public;user_line_permissions